/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AssignmentMain;
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ranul    10602053
 */
public class frameMain extends javax.swing.JFrame {
    //Resource creation.
    private Controller controller;
    private ResultSet resultSet;
    private ResultSetMetaData metaData;
    private DefaultListModel invoiceData;
    private ControllerPayment obj= new ControllerPayment();
    
    private String selectedValue;
    private String[] selectedValueArray;
    private String itemName;
    int checkQuantity;
    
    private String invoiceHeader= "Item ID          Item Name          Item Category"+
            "          Unit Price          Quantity";
    /**
     * Creates new form frameMain
     */
    public frameMain() {
        initComponents();
        buttonAdd.setEnabled(false);//Hide the add to cart button during initialization.
        buttonPlaceOrder.setEnabled(false);
        invoiceData= new DefaultListModel();
        controller= new Controller();
        invoiceData.addElement(invoiceHeader);
        listBoxInvoice.setModel(invoiceData);
        panelCheckout.setVisible(false);
        
        panelCashPayment.setVisible(true);
        panelCreditCardPayment.setVisible(false);
        panelDebitCardPayment.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelSearchItem = new javax.swing.JPanel();
        textBoxSearch = new javax.swing.JTextField();
        labelSearchBox = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBoxSearchItems = new javax.swing.JList<>();
        panelAddItem = new javax.swing.JPanel();
        labelItemId = new javax.swing.JLabel();
        labelItemCategory = new javax.swing.JLabel();
        labelItemName = new javax.swing.JLabel();
        labelItemUnitPrice = new javax.swing.JLabel();
        labelItemQuantity = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        textBoxQuantity = new javax.swing.JTextField();
        labelQuantitySelect = new javax.swing.JLabel();
        labelItemIdData = new javax.swing.JLabel();
        labelItemCategoryData = new javax.swing.JLabel();
        labelItemNameData = new javax.swing.JLabel();
        labelItemUnitPriceData = new javax.swing.JLabel();
        labelItemQuantityData = new javax.swing.JLabel();
        panelInvoice = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBoxInvoice = new javax.swing.JList<>();
        panelPayment = new javax.swing.JPanel();
        labelTotalPrice = new javax.swing.JLabel();
        buttonPlaceOrder = new javax.swing.JButton();
        labelTotalPriceData = new javax.swing.JLabel();
        panelCheckout = new javax.swing.JPanel();
        comboBoxPaymentSelector = new javax.swing.JComboBox<>();
        panelPaymentMethod = new javax.swing.JPanel();
        panelCashPayment = new java.awt.Panel();
        textBoxCashTendered = new javax.swing.JTextField();
        buttonGetBalance = new javax.swing.JButton();
        textBoxShowBalance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCreditCardPayment = new javax.swing.JPanel();
        textBoxCreditCard = new javax.swing.JTextField();
        buttonValidateCreditCard = new javax.swing.JButton();
        labelCreditCardNumber = new javax.swing.JLabel();
        panelDebitCardPayment = new javax.swing.JPanel();
        textBoxDebitCard = new javax.swing.JTextField();
        labelDebitCardNumber = new javax.swing.JLabel();
        buttonValidateDebitCard = new javax.swing.JButton();
        labelPaymentTotalPrice = new javax.swing.JLabel();
        textBoxPaymentTotalPrice = new javax.swing.JTextField();
        labelPaymentMethod = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Store POS");

        panelMain.setBackground(new java.awt.Color(255, 255, 204));

        textBoxSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBoxSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBoxSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textBoxSearchKeyReleased(evt);
            }
        });

        labelSearchBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSearchBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSearchBox.setText("Search Item");

        listBoxSearchItems.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        listBoxSearchItems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBoxSearchItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listBoxSearchItems.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listBoxSearchItemsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listBoxSearchItems);

        javax.swing.GroupLayout panelSearchItemLayout = new javax.swing.GroupLayout(panelSearchItem);
        panelSearchItem.setLayout(panelSearchItemLayout);
        panelSearchItemLayout.setHorizontalGroup(
            panelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchItemLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSearchItemLayout.createSequentialGroup()
                        .addComponent(labelSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(textBoxSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchItemLayout.setVerticalGroup(
            panelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchItemLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        panelAddItem.setBackground(new java.awt.Color(255, 204, 204));

        labelItemId.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelItemId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelItemId.setText("Item ID");

        labelItemCategory.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelItemCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelItemCategory.setText("Item Category");

        labelItemName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelItemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelItemName.setText("Item Name");

        labelItemUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelItemUnitPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelItemUnitPrice.setText("Unit Price");

        labelItemQuantity.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelItemQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelItemQuantity.setText("Quantity");

        buttonAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        textBoxQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textBoxQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelQuantitySelect.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelQuantitySelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelQuantitySelect.setText("Quantity");

        labelItemIdData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelItemIdData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelItemCategoryData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelItemCategoryData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelItemNameData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelItemNameData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelItemUnitPriceData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelItemUnitPriceData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelItemQuantityData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout panelAddItemLayout = new javax.swing.GroupLayout(panelAddItem);
        panelAddItem.setLayout(panelAddItemLayout);
        panelAddItemLayout.setHorizontalGroup(
            panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddItemLayout.createSequentialGroup()
                .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddItemLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(labelQuantitySelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(textBoxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(panelAddItemLayout.createSequentialGroup()
                        .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAddItemLayout.createSequentialGroup()
                                .addComponent(labelItemIdData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelItemCategoryData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAddItemLayout.createSequentialGroup()
                                .addComponent(labelItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddItemLayout.createSequentialGroup()
                                .addComponent(labelItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelItemUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAddItemLayout.createSequentialGroup()
                                .addComponent(labelItemNameData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelItemUnitPriceData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelItemQuantityData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAddItemLayout.setVerticalGroup(
            panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelItemUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelItemIdData, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(labelItemCategoryData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelItemNameData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelItemUnitPriceData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelItemQuantityData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelQuantitySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textBoxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );

        panelInvoice.setBackground(new java.awt.Color(153, 255, 204));

        listBoxInvoice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        listBoxInvoice.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " ", "\t" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listBoxInvoice);

        javax.swing.GroupLayout panelInvoiceLayout = new javax.swing.GroupLayout(panelInvoice);
        panelInvoice.setLayout(panelInvoiceLayout);
        panelInvoiceLayout.setHorizontalGroup(
            panelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInvoiceLayout.setVerticalGroup(
            panelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalPrice.setText("Total Price");

        buttonPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonPlaceOrder.setText("Place Order");
        buttonPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlaceOrderActionPerformed(evt);
            }
        });

        labelTotalPriceData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelTotalPriceData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalPriceData.setText("---");

        javax.swing.GroupLayout panelPaymentLayout = new javax.swing.GroupLayout(panelPayment);
        panelPayment.setLayout(panelPaymentLayout);
        panelPaymentLayout.setHorizontalGroup(
            panelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaymentLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPaymentLayout.createSequentialGroup()
                        .addComponent(labelTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTotalPriceData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPaymentLayout.setVerticalGroup(
            panelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaymentLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotalPriceData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(buttonPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSearchItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(panelPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSearchItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comboBoxPaymentSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit Card", "Debit Card" }));
        comboBoxPaymentSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPaymentSelectorActionPerformed(evt);
            }
        });

        panelCashPayment.setBackground(new java.awt.Color(255, 255, 51));
        panelCashPayment.setPreferredSize(new java.awt.Dimension(500, 300));

        textBoxCashTendered.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBoxCashTendered.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBoxCashTendered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxCashTenderedActionPerformed(evt);
            }
        });

        buttonGetBalance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        buttonGetBalance.setText("Pay");
        buttonGetBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetBalanceActionPerformed(evt);
            }
        });

        textBoxShowBalance.setEditable(false);
        textBoxShowBalance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBoxShowBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cash Tendered");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Balance");

        javax.swing.GroupLayout panelCashPaymentLayout = new javax.swing.GroupLayout(panelCashPayment);
        panelCashPayment.setLayout(panelCashPaymentLayout);
        panelCashPaymentLayout.setHorizontalGroup(
            panelCashPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCashPaymentLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelCashPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCashPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCashPaymentLayout.createSequentialGroup()
                        .addGroup(panelCashPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBoxShowBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(textBoxCashTendered))
                        .addGap(48, 48, 48))
                    .addGroup(panelCashPaymentLayout.createSequentialGroup()
                        .addComponent(buttonGetBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelCashPaymentLayout.setVerticalGroup(
            panelCashPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCashPaymentLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelCashPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textBoxCashTendered, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(buttonGetBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(panelCashPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textBoxShowBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCreditCardPayment.setBackground(new java.awt.Color(51, 255, 51));

        textBoxCreditCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBoxCreditCard.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonValidateCreditCard.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonValidateCreditCard.setText("Pay");
        buttonValidateCreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidateCreditCardActionPerformed(evt);
            }
        });

        labelCreditCardNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCreditCardNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCreditCardNumber.setText("Enter Credit Card Number");

        javax.swing.GroupLayout panelCreditCardPaymentLayout = new javax.swing.GroupLayout(panelCreditCardPayment);
        panelCreditCardPayment.setLayout(panelCreditCardPaymentLayout);
        panelCreditCardPaymentLayout.setHorizontalGroup(
            panelCreditCardPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditCardPaymentLayout.createSequentialGroup()
                .addGroup(panelCreditCardPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCreditCardPaymentLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(labelCreditCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCreditCardPaymentLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(textBoxCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCreditCardPaymentLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(buttonValidateCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelCreditCardPaymentLayout.setVerticalGroup(
            panelCreditCardPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditCardPaymentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelCreditCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(textBoxCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(buttonValidateCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        panelDebitCardPayment.setBackground(new java.awt.Color(255, 0, 0));
        panelDebitCardPayment.setPreferredSize(new java.awt.Dimension(500, 300));

        textBoxDebitCard.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textBoxDebitCard.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelDebitCardNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDebitCardNumber.setText("Enter Debit Card Number");

        buttonValidateDebitCard.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonValidateDebitCard.setText("Pay");
        buttonValidateDebitCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidateDebitCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDebitCardPaymentLayout = new javax.swing.GroupLayout(panelDebitCardPayment);
        panelDebitCardPayment.setLayout(panelDebitCardPaymentLayout);
        panelDebitCardPaymentLayout.setHorizontalGroup(
            panelDebitCardPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDebitCardPaymentLayout.createSequentialGroup()
                .addGroup(panelDebitCardPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDebitCardPaymentLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(labelDebitCardNumber))
                    .addGroup(panelDebitCardPaymentLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(buttonValidateDebitCard, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDebitCardPaymentLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(textBoxDebitCard, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDebitCardPaymentLayout.setVerticalGroup(
            panelDebitCardPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDebitCardPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDebitCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBoxDebitCard, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(buttonValidateDebitCard, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout panelPaymentMethodLayout = new javax.swing.GroupLayout(panelPaymentMethod);
        panelPaymentMethod.setLayout(panelPaymentMethodLayout);
        panelPaymentMethodLayout.setHorizontalGroup(
            panelPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaymentMethodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDebitCardPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPaymentMethodLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCreditCardPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPaymentMethodLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(panelCashPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(145, Short.MAX_VALUE)))
        );
        panelPaymentMethodLayout.setVerticalGroup(
            panelPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaymentMethodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDebitCardPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(panelPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPaymentMethodLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCreditCardPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
            .addGroup(panelPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPaymentMethodLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(panelCashPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        labelPaymentTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPaymentTotalPrice.setText("Total Price");

        textBoxPaymentTotalPrice.setEditable(false);
        textBoxPaymentTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textBoxPaymentTotalPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelPaymentMethod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPaymentMethod.setText("Payment Method");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCheckoutLayout = new javax.swing.GroupLayout(panelCheckout);
        panelCheckout.setLayout(panelCheckoutLayout);
        panelCheckoutLayout.setHorizontalGroup(
            panelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckoutLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCheckoutLayout.createSequentialGroup()
                        .addComponent(labelPaymentTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textBoxPaymentTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(labelPaymentMethod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxPaymentSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelCheckoutLayout.setVerticalGroup(
            panelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckoutLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPaymentTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textBoxPaymentTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPaymentSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Adds an item to the cart.
     * @param evt 
     */
    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        try{
            int quantity= Integer.parseInt(textBoxQuantity.getText());
            try{
                //Handle the ExceedsInventory exception.
                controller.checkQuantity(quantity, checkQuantity);
                if(quantity>= 1){
                controller.setItemQuantity(quantity);
                controller.insertToOrder(); //Inserts the selected list row to the order class.
                String[] array= controller.getSelectedValueArray(); //Adds the selected item to the invoice list.
                String joinedString= "";
                for(int i= 0; i< 5; i++){  
                    if(i== 4){
                        array[i]= String.valueOf(quantity);
                    }
                    joinedString= joinedString+ array[i]+ "          ";
                }
                invoiceData.addElement(joinedString);
                listBoxInvoice.setModel(invoiceData);
                
                //Calculate the total price each time an item is added.
                float totalPrice= controller.getTotalPrice();
                labelTotalPriceData.setText(String.valueOf(totalPrice));
                buttonPlaceOrder.setEnabled(true);
                }
            }
            catch(ExceedsInventory e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please select an item quantity!", "Select Quantity", JOptionPane.WARNING_MESSAGE);
            //System.out.println("Invalid input! Please enter an integer. "+ e.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            //System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    /**
     * Searches for items in the database when the user types in the text box.
     * @param evt 
     */
    private void textBoxSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBoxSearchKeyReleased
        // Searches for items from the database.
        if(textBoxSearch.getText()!= ""){
            //Simple validation.
            controller.setSearchTerm(textBoxSearch.getText());
            resultSet= controller.getSearchResult();
            metaData= controller.getSearchResultMetaData();
            
            try{
                DefaultListModel listModel= new DefaultListModel(); //The list model contains data to be added to the jListBox.
                while(resultSet.next()){
                    listModel.addElement(resultSet.getInt("itemId")+ "          "+ resultSet.getString("itemName")+ "          " +resultSet.getString("itemCategory")+ 
                            "          "+ resultSet.getFloat("unitPrice")+ "          "+ resultSet.getInt("quantity"));
                }
                listBoxSearchItems.setModel(listModel);
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }   
    }//GEN-LAST:event_textBoxSearchKeyReleased

    /**
     * Sends the selected item to be stored temporarily and sets the item details in labels.
     * @param evt 
     */
    private void listBoxSearchItemsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listBoxSearchItemsValueChanged

        //Shows the selected item details in a set of labels. 
        controller.setSelectedValue(listBoxSearchItems.getSelectedValue());
        selectedValueArray= controller.getSelectedValueArray();
        labelItemIdData.setText(selectedValueArray[0]);
        labelItemNameData.setText(selectedValueArray[1]);
        labelItemCategoryData.setText(selectedValueArray[2]);
        labelItemUnitPriceData.setText(selectedValueArray[3]);
        labelItemQuantityData.setText(selectedValueArray[4]);
        
        checkQuantity= Integer.parseInt(selectedValueArray[4]); //Enables the add button if quantity>= 1.
        if(checkQuantity>= 1){
            buttonAdd.setEnabled(true);
        }
        else{
            buttonAdd.setEnabled(false);
        }
        //System.out.println(selectedValue);
    }//GEN-LAST:event_listBoxSearchItemsValueChanged

    /**
     * Shows the payment panel.
     * @param evt 
     */
    private void buttonPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlaceOrderActionPerformed
        obj.setTotalAmount(controller.getTotalPrice());
        textBoxPaymentTotalPrice.setText(String.valueOf(controller.getTotalPrice()));
        panelMain.setVisible(false);
        panelCheckout.setVisible(true);
        
    }//GEN-LAST:event_buttonPlaceOrderActionPerformed

    private void textBoxCashTenderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxCashTenderedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxCashTenderedActionPerformed

    private void buttonGetBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetBalanceActionPerformed
        // TODO add your handling code here:
        //occurs when button is clicked
        //obj is controller payment object
        if(comboBoxPaymentSelector.getSelectedItem()=="Cash")
        {
            try{
                float amount=Float.parseFloat(textBoxCashTendered.getText());//get the amount
                obj.setCashvalue(amount); //set cash value
                obj.setOrderId(controller.getOrderId());  //first get order id from controller and set order id
                textBoxShowBalance.setText(String.valueOf(obj.cashPayment()));
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(panelPayment, "Insufficient amount!");
            }      
        }     
    }//GEN-LAST:event_buttonGetBalanceActionPerformed

    private void comboBoxPaymentSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPaymentSelectorActionPerformed
        // TODO add your handling code here:
        if(comboBoxPaymentSelector.getSelectedItem()=="Cash"){
            panelCashPayment.setVisible(true);
            panelCreditCardPayment.setVisible(false);
            panelDebitCardPayment.setVisible(false);
        }
        else if(comboBoxPaymentSelector.getSelectedItem()== "Credit Card"){
            panelCashPayment.setVisible(false);
            panelCreditCardPayment.setVisible(true);
            panelDebitCardPayment.setVisible(false);
        }
        else if(comboBoxPaymentSelector.getSelectedItem()== "Debit Card"){
            panelCashPayment.setVisible(false);
            panelCreditCardPayment.setVisible(false);
            panelDebitCardPayment.setVisible(true);
        }
        
    }//GEN-LAST:event_comboBoxPaymentSelectorActionPerformed
/**
 * occurs when button is clicked
 * @param evt 
 */
    private void buttonValidateCreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidateCreditCardActionPerformed
        // TODO add your handling code here:
        //occurs when button is clicked
        //obj is controller payment object
        if(comboBoxPaymentSelector.getSelectedItem()=="Credit Card")
        {
            String number=textBoxCreditCard.getText();
            obj.setTotalAmount(controller.getTotalPrice());//get total price
            obj.setOrderId(controller.getOrderId());//get order id
            obj.setCardNumber(number); //set card number
            obj.setCardType((String) comboBoxPaymentSelector.getSelectedItem()); //set card type
            obj.cardPayment(); //call card payment which is in controller payment
        }
    }//GEN-LAST:event_buttonValidateCreditCardActionPerformed

    private void buttonValidateDebitCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidateDebitCardActionPerformed
            //occurs when button is clicked
        //obj is controller payment object      
        if(comboBoxPaymentSelector.getSelectedItem()=="Debit Card")
        {
            String number=textBoxDebitCard.getText();
            obj.setTotalAmount(controller.getTotalPrice());//get total price
            obj.setOrderId(controller.getOrderId());//get order id
            obj.setCardNumber(number);//set card number
            obj.setCardType((String) comboBoxPaymentSelector.getSelectedItem());//set card type
            obj.cardPayment();//call card payment which is in controller payment
        }
    }//GEN-LAST:event_buttonValidateDebitCardActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelCheckout.setVisible(false);
        panelMain.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonGetBalance;
    private javax.swing.JButton buttonPlaceOrder;
    private javax.swing.JButton buttonValidateCreditCard;
    private javax.swing.JButton buttonValidateDebitCard;
    private javax.swing.JComboBox<String> comboBoxPaymentSelector;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCreditCardNumber;
    private javax.swing.JLabel labelDebitCardNumber;
    private javax.swing.JLabel labelItemCategory;
    private javax.swing.JLabel labelItemCategoryData;
    private javax.swing.JLabel labelItemId;
    private javax.swing.JLabel labelItemIdData;
    private javax.swing.JLabel labelItemName;
    private javax.swing.JLabel labelItemNameData;
    private javax.swing.JLabel labelItemQuantity;
    private javax.swing.JLabel labelItemQuantityData;
    private javax.swing.JLabel labelItemUnitPrice;
    private javax.swing.JLabel labelItemUnitPriceData;
    private javax.swing.JLabel labelPaymentMethod;
    private javax.swing.JLabel labelPaymentTotalPrice;
    private javax.swing.JLabel labelQuantitySelect;
    private javax.swing.JLabel labelSearchBox;
    private javax.swing.JLabel labelTotalPrice;
    private javax.swing.JLabel labelTotalPriceData;
    private javax.swing.JList<String> listBoxInvoice;
    private javax.swing.JList<String> listBoxSearchItems;
    private javax.swing.JPanel panelAddItem;
    private java.awt.Panel panelCashPayment;
    private javax.swing.JPanel panelCheckout;
    private javax.swing.JPanel panelCreditCardPayment;
    private javax.swing.JPanel panelDebitCardPayment;
    private javax.swing.JPanel panelInvoice;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPayment;
    private javax.swing.JPanel panelPaymentMethod;
    private javax.swing.JPanel panelSearchItem;
    private javax.swing.JTextField textBoxCashTendered;
    private javax.swing.JTextField textBoxCreditCard;
    private javax.swing.JTextField textBoxDebitCard;
    private javax.swing.JTextField textBoxPaymentTotalPrice;
    private javax.swing.JTextField textBoxQuantity;
    private javax.swing.JTextField textBoxSearch;
    private javax.swing.JTextField textBoxShowBalance;
    // End of variables declaration//GEN-END:variables
}
